name: Vercel Preview Deployment
env:
   VERCEL_ORG_ID: ${{ jJ86BJnr4VE32OXx40k8Sz6B }}
   VERCEL_PROJECT_ID: ${{ prj_alEVGh4kGDZA2Ra6G3m19hM2JvVq }}
on:
   workflow_run:
      workflows: ["End-to-end tests"]
      types:
         - completed
jobs:
   Deploy-Preview:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - name: Install Vercel CLI
           run: npm install --global vercel@latest

         - name: Pull Vercel Environment Information
           run: vercel pull --yes --environment=preview --token=${{ P7qJ4cqaIaswZ38ITZja7buq  }}

         - name: Build Project Artifacts
           run: vercel build --token=${{ P7qJ4cqaIaswZ38ITZja7buq  }}

         - name: Deploy Project Artifacts to Vercel
           run: vercel deploy --prebuilt --token=${{ P7qJ4cqaIaswZ38ITZja7buq  }}
